[package]
name = "hacklet-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
argh = "0.1.12"
byteorder = "1.5.0"
libftdi1-sys = "1.1.3"
log = "0.4.22"
nom = "7.1.3"
mockall = "0.13.0"
tokio = "1.41.0"
tokio-serial = "5.4.4"
tokio-macros = "2.4.0"
